/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ozkan
 */
public class Urunler extends javax.swing.JFrame {

    /**
     * Creates new form Urunler
     */
    public Urunler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setEnabled(false);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Ürün Grubu");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setEnabled(false);
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Marka");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Yeni Ürün Kodu Kaydı");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList3.setToolTipText("Silmek İstediğiniz Ürünü Seçmek İçin Çift Tıklayınız");
        jList3.setEnabled(false);
        jList3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList3FocusGained(evt);
            }
        });
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Kayıtlı Ürün Kodları");

        jTextField1.setToolTipText("Kaydedilecek Kodu Giriniz");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1MouseEntered(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Ürün Kodu");

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("+");
        jButton1.setToolTipText("Ürün Kodu Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton2.setText("SİL");
        jButton2.setToolTipText("Kayıtlı Ürün Kodunu Sil");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1)
                                .addGap(160, 160, 160)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addGap(42, 42, 42)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jButton1)))
                .addGap(120, 120, 120))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int grupId, markaId, urunKodu;
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
       if(!jTextField1.getText().equals(null)){
           jList1.setEnabled(true);
       }
        jList1.setEnabled(true);
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MouseClicked
    public void UrunlerAcilis(){
        UrunGrubuAcilis();
        MarkalarAcilis();
        UrunKoduAcilis();
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        jList1.setEnabled(true);
        UrunlerAcilis();
    }//GEN-LAST:event_formComponentShown

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        jList2.setEnabled(true);
        jList1.setEnabled(true);
        jList3.setEnabled(false);
        jButton2.setEnabled(false);
        jTextField1.setText("");
        //List hedef = (List)evt.getSource();
        String grup; //= hedef.get(jList1.getSelectedIndex()).toString();
        grup = jList1.getSelectedValue();
        System.out.println(grup);
        try {
            this.grupId = new codes.urun().GrupIdAl(grup);
        } catch (SQLException ex) {
            Logger.getLogger(Urunler.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(this.grupId);
        UrunKoduDetayArama();
    }//GEN-LAST:event_jList1MouseClicked

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
         if(!jTextField1.getText().equals(null)){
           jList1.setEnabled(true);
       }
        jList1.setEnabled(true);
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
        jList3.setEnabled(false);
        jList3.setEnabled(false);
        jButton2.setEnabled(false);
        jTextField1.setText("");
        String marka; //= hedef.get(jList1.getSelectedIndex()).toString();
        marka = jList2.getSelectedValue();
        System.out.println(marka);
        try {
            this.markaId = new codes.urun().MarkaIdAl(marka);
        } catch (SQLException ex) {
            Logger.getLogger(Urunler.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(this.markaId);
        UrunKoduDetayArama();
    }//GEN-LAST:event_jList2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(markaId==0 || grupId==0){
            JOptionPane.showMessageDialog(this, "Lütfen Ürün Grubu ve Marka Seçiniz");
        }
        else{
          if(!jTextField1.getText().equals("")){
          codes.urun urunler = new codes.urun();
        boolean durum = false;
        try {
            durum = urunler.UrunEkle(jTextField1.getText().toUpperCase().trim(), this.grupId, this.markaId);
            if(durum){
                
                JOptionPane.showMessageDialog(this, "Ürün Eklendi");
                UrunKoduAcilis();
                this.markaId=0;
                this.grupId=0;
                jList1.setSelectedIndex(0);
                jList2.setSelectedIndex(0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Urunler.class.getName()).log(Level.SEVERE, null, ex);
        }   
            }
            else
                JOptionPane.showMessageDialog(this, "Ürün Kodunu Giriniz");
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         boolean durum = false;
        try {
            int id=0;
            id = new codes.urun().UrunIdBul(jTextField1.getText().trim(), this.markaId, this.grupId);
            if(id>0){
                durum = new codes.urun().UrunSil(id);
            if(durum){
                JOptionPane.showMessageDialog(this, "Kayıt Başarıyla Silindi");
                jTextField1.setText("");
                UrunKoduAcilis();
                jList3.setSelectedIndex(0);
                jList2.setSelectedIndex(0);
                jList1.setSelectedIndex(0);
                this.markaId=0;
                this.grupId=0;
            }else{
                JOptionPane.showMessageDialog(this, "Silinirken Hata Oldu. Silinemedi");
            }
            }else{
               JOptionPane.showMessageDialog(this, "Ürün Bulunamadı");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Eklemeler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList3FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jList3FocusGained

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        // TODO add your handling code here:
      if (evt.getClickCount() ==2) {
          jList3.setEnabled(true);
          jButton2.setEnabled(true);
      }
      if(jList3.isEnabled()){
        String urunKod = jList3.getSelectedValue().toString();
        jTextField1.setText(urunKod);
      }
    }//GEN-LAST:event_jList3MouseClicked

    private void jTextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MouseEntered
    public void UrunGrubuAcilis(){
        List<codes.urun> gruplist = null;
        DefaultListModel listmodel = new DefaultListModel();
        listmodel.clear();
        try {
            gruplist = new codes.urun().UrunGrubuHepsi();
        } catch (SQLException ex) {
            Logger.getLogger(Eklemeler.class.getName()).log(Level.SEVERE, null, ex);
        }
        Vector[] v = new Vector[gruplist.size()];
        for(int n=0;n<gruplist.size();n++){
            v[n] = new Vector();
            listmodel.add(n, gruplist.get(n).getUrun_grubu());
        }
        jList1.setModel(listmodel);
        jList1.repaint();
    }
    public void MarkalarAcilis(){
           List<codes.urun> gruplist = null;
        DefaultListModel listmodel = new DefaultListModel();
        listmodel.clear();
        try {
            gruplist = new codes.urun().MarkalarHepsi();
        } catch (SQLException ex) {
            Logger.getLogger(Eklemeler.class.getName()).log(Level.SEVERE, null, ex);
        }
        Vector[] v = new Vector[gruplist.size()];
        for(int n=0;n<gruplist.size();n++){
            v[n] = new Vector();
            listmodel.add(n, gruplist.get(n).getUrun_marka());
        }
        jList2.setModel(listmodel);
        jList2.repaint();
    }
    public void UrunKoduAcilis(){
         List<codes.urun> gruplist = null;
        DefaultListModel listmodel = new DefaultListModel();
        listmodel.clear();
        try {
            gruplist = new codes.urun().UrunKoduHepsi();
        } catch (SQLException ex) {
            Logger.getLogger(Eklemeler.class.getName()).log(Level.SEVERE, null, ex);
        }
        Vector[] v = new Vector[gruplist.size()];
        for(int n=0;n<gruplist.size();n++){
            v[n] = new Vector();
            listmodel.add(n, gruplist.get(n).getUrun_kodu());
        }
        jList3.setModel(listmodel);
        jList3.repaint();
    }
    public void UrunKoduDetayArama(){
        List<codes.urun> gruplist = null;
        DefaultListModel listmodel = new DefaultListModel();
        listmodel.clear();
        try {
            gruplist = new codes.urun().UrunKoduBul(markaId, grupId);
        } catch (SQLException ex) {
            Logger.getLogger(Eklemeler.class.getName()).log(Level.SEVERE, null, ex);
        }
        Vector[] v = new Vector[gruplist.size()];
        for(int n=0;n<gruplist.size();n++){
            v[n] = new Vector();
            listmodel.add(n, gruplist.get(n).getUrun_kodu());
        }
        jList3.setModel(listmodel);
        jList3.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urunler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urunler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urunler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urunler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urunler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
